let data = [
    {
        name: "Four card feature section",
        URL: "../portfolio/frontendmentor/four-card-feature-section/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/four-card-feature-section.jpg",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Huddle landing page",
        URL: "../portfolio/frontendmentor/huddle-landing-page-with-single-introductory-section/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/huddle-landing-page-with-single-introductory-section.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Ping coming soon page",
        URL: "../portfolio/frontendmentor/ping-single-column-coming-soon-page/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/ping-single-column-coming-soon-page.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Single price grid component",
        URL: "../portfolio/frontendmentor/single-price-grid-component/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/single-price-grid-component.jpg",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Intro component with sign-up form",
        URL: "../portfolio/frontendmentor/Intro-component-with-sign-up-form/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/intro-component-with-sign-up-form.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Base Apparel coming soon page",
        URL: "../portfolio/frontendmentor/base-apparel-coming-soon-page/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/base-apparel-coming-soon.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Social proof section",
        URL: "../portfolio/frontendmentor/social-proof-section/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/social-proof-section.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "FAQ accordion card",
        URL: "../portfolio/frontendmentor/FAQ-accordion-card/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/FAQ-accordion-card.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Profile card component",
        URL: "../portfolio/frontendmentor/profile-card-component/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/profile-card-component.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Preview card component",
        URL: "../portfolio/frontendmentor/3-column-preview-card-component/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/3-column-preview-card-component.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Meet Landing page",
        URL: "../portfolio/frontendmentor/meet-landing-page/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/meet-landing-page.jpg",
        frontendmentor: true,
        freelance: false,
        difficulty: "newbie",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "CARAT Landing page",
        URL: "https://nitalewska.github.io/Kwork-CARAT/",
        thumbnail: "../portfolio/frontendmentor/thumbnails/CARAT-landing-page.jpg",
        frontendmentor: false,
        freelance: true,
        difficulty: "",
        favourite: true,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Quiz",
        URL: "https://nitalewska.github.io/quiz-react/",
        thumbnail: "../portfolio/frontendmentor/thumbnails/quiz.jpg",
        frontendmentor: false,
        freelance: false,
        difficulty: "",
        favourite: true,
        pet: true,
        langs: "HTML/CSS/ReactJS/API",
        description: ""
    },
    {
        name: "Clipboard Landing page",
        URL: "https://nitalewska.github.io/clipboard-landing-page/",
        thumbnail: "../portfolio/frontendmentor/thumbnails/clipboard-landing-page.jpg",
        frontendmentor: true,
        freelance: false,
        difficulty: "junior",
        favourite: true,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "Testimonials Grid Section",
        URL: "../portfolio/frontendmentor/testimonials-grid-section/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/testimonials-grid-section.png",
        frontendmentor: true,
        freelance: false,
        difficulty: "junior",
        favourite: false,
        pet: false,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "3D Artist's Portfolio",
        URL: "../portfolio/frontendmentor/dzirun_portfolio/index.html",
        thumbnail: "../portfolio/frontendmentor/thumbnails/dzirun_portfolio.jpg",
        frontendmentor: false,
        freelance: false,
        difficulty: "",
        favourite: false,
        pet: true,
        langs: "HTML/CSS",
        description: ""
    },
    {
        name: "JS Calculator",
        URL: "https://nitalewska.github.io/calc_js_basics/",
        thumbnail: "../portfolio/frontendmentor/thumbnails/calc-js.jpg",
        frontendmentor: false,
        freelance: false,
        difficulty: "",
        favourite: true,
        pet: true,
        langs: "HTML/CSS/JS",
        description: ""
    },
    {
        name: "News Homepage",
        URL: "https://nitalewska.github.io/news-homepage/",
        thumbnail: "../portfolio/frontendmentor/thumbnails/news-homepage.jpg",
        frontendmentor: true,
        freelance: false,
        difficulty: "junior",
        favourite: true,
        pet: false,
        langs: "HTML/CSS/JS",
        description: ""
    },
    {
        name: "Advice generator app",
        URL: "https://nitalewska.github.io/Advice-generator-app/",
        thumbnail: "../portfolio/frontendmentor/thumbnails/Advice-generator-app.jpg",
        frontendmentor: true,
        freelance: false,
        difficulty: "junior",
        favourite: true,
        pet: false,
        langs: "HTML/CSS/JS/API",
        description: ""
    },
    {
        name: "Tenzies",
        URL: "https://nitalewska.github.io/tenzies-game-react/",
        thumbnail: "../portfolio/frontendmentor/thumbnails/tenzies-game-react.jpg",
        frontendmentor: false,
        freelance: false,
        difficulty: "",
        favourite: true,
        pet: true,
        langs: "HTML/CSS/JS/ReactJS",
        description: ""
    },
    {
        name: "Health Test",
        URL: "https://nitalewska.github.io/health_test/",
        thumbnail: "../portfolio/frontendmentor/thumbnails/health_test.jpg",
        frontendmentor: false,
        freelance: false,
        difficulty: "",
        favourite: false,
        pet: true,
        langs: "HTML/CSS/JS/ReactJS",
        description: ""
    }
]

export default data